### ISSUE TITLE
Images from docker compose are marked private

### ISSUE THREAD

**Issue by strazzere** [polyswarm/polyswarmd#13]
https://github.com/polyswarm/polyswarmd/blob/2abb4d1389dcf4c33596251215ecbbc2f11df133/docker/docker-compose-priv-testnet.yml#L17

Is this intentional or a mistake?

Would be nice if the docker-compose files in the public repos "just worked".

**Comment by myhndl** [comment]
Yeah totally agree.

We're in the process of moving from gitlab.com to a self-hosted GitLab instance, which is blocking us making this repo public due to dumb gitlab.com versus self-hosting permission not-parity. We're making the transition this weekend, so this (and other) repos should become public directly on our GitLab.

That being said, our stopgap had been pushing to GitHub as well and I don't see a reason to not also push this one to GitHub. 

Checking with team, will get back ASAP.

**Comment by myhndl** [comment]
@mjkoo for visibility on this issue.

**Comment by strazzere** [comment]
Not a big deal - more just pointing it out.

Setting up and following the current README instructions are less than ideal if a `docker-compose -f blah up` would work :)

**Comment by myhndl** [comment]
Totally agree - I appreciate the ticket :)

**Comment by myhndl** [comment]
Update on this: we completed migration to a self-hosted instance, which should unblock our permission-ing issues, including this one. Will target for addressing before Beta (31st)

**Comment by myhndl** [comment]
We've since published all of our images on Docker Hub: https://hub.docker.com/u/polyswarm/

The referenced file no longer exists; it has been moved to the orchestration repo: https://github.com/polyswarm/orchestration

To my knowledge all Docker Compose YAMLs now exclusively reference Docker Hub images.
